logsINFO:root:ping() got an unexpected keyword argument 'count'
INFO:tornado.access:200 POST /ping (172.109.0.1) 1.68ms
INFO:root:maximum recursion depth exceeded
ERROR:tornado.application:Uncaught exception POST /ping (172.109.0.1)
HTTPServerRequest(protocol='http', host='localhost:9898', method='POST', uri='/ping', version='HTTP/1.1', remote_ip='172.109.0.1', headers={'Content-Type': 'text/plain', 'User-Agent': 'PostmanRuntime/7.32.2', 'Accept': '*/*', 'Postman-Token': '55f13f58-bdb4-4a16-b9e0-22206a2afc4e', 'Host': 'localhost:9898', 'Accept-Encoding': 'gzip, deflate, br', 'Connection': 'keep-alive', 'Content-Length': '20'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1443, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "nettools.py", line 47, in post
    self.write(respuesta)
  File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 692, in write
    chunk = escape.json_encode(chunk)
  File "/usr/local/lib/python3.8/site-packages/tornado/escape.py", line 88, in json_encode
    return json.dumps(value).replace("</", "<\\/")
  File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
RecursionError: maximum recursion depth exceeded while encoding a JSON object
ERROR:tornado.access:500 POST /ping (172.109.0.1) 4.54ms
INFO:root:maximum recursion depth exceeded
ERROR:tornado.application:Uncaught exception POST /ping (172.109.0.1)
HTTPServerRequest(protocol='http', host='localhost:9898', method='POST', uri='/ping', version='HTTP/1.1', remote_ip='172.109.0.1', headers={'Content-Type': 'text/plain', 'User-Agent': 'PostmanRuntime/7.32.2', 'Accept': '*/*', 'Postman-Token': '77c1741a-f53a-4777-8d3b-b8125250c73d', 'Host': 'localhost:9898', 'Accept-Encoding': 'gzip, deflate, br', 'Connection': 'keep-alive', 'Content-Length': '20'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1443, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "nettools.py", line 47, in post
    self.write(respuesta)
  File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 692, in write
    chunk = escape.json_encode(chunk)
  File "/usr/local/lib/python3.8/site-packages/tornado/escape.py", line 88, in json_encode
    return json.dumps(value).replace("</", "<\\/")
  File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
RecursionError: maximum recursion depth exceeded while encoding a JSON object
ERROR:tornado.access:500 POST /ping (172.109.0.1) 3.31ms
INFO:root:maximum recursion depth exceeded
